[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic", "metrics"]}
tracing-subscriber = { workspace = true }
tracing = { workspace = true }